#!/bin/bash

if [ "$1" == "ati" ];
then
VIDEO_DRIVER="fglrx"
    VIDEO_MANUFACTURER="ATI"
elif [ "$1" == "nvidia" ];
then
VIDEO_DRIVER="nvidia-current"
    VIDEO_MANUFACTURER="NVIDIA"
elif [ "$1" == "intel" ];
then
VIDEO_DRIVER="i965-va-driver"
    VIDEO_MANUFACTURER="INTEL"
else
echo ""
    echo "$(tput setaf 1)$(tput bold)ERROR: Please provide the video card manufaturer parameter (ati / nvidia / intel)$(tput sgr0)"
    echo ""
    exit
fi

HOME_DIRECTORY="/home/xbmc/"
TEMP_DIRECTORY=$HOME_DIRECTORY"temp/"
SOURCES_FILE="/etc/apt/sources.list"
SOURCES_BACKUP_FILE="/etc/apt/sources.list.bak"
ENVIRONMENT_FILE="/etc/environment"
ENVIRONMENT_BACKUP_FILE="/etc/environment.bak"
INIT_FILE="/etc/init.d/xbmc"
XBMC_ADDONS_DIR="/home/xbmc/.xbmc/addons/"
XBMC_USERDATA_DIR="/home/xbmc/.xbmc/userdata/"
XBMC_ADVANCEDSETTINGS_FILE=$XBMC_USERDATA_DIR"advancedsettings.xml"
XBMC_ADVANCEDSETTINGS_BACKUP_FILE=$XBMC_USERDATA_DIR"advancedsettings.xml.bak"
XWRAPPER_BACKUP_FILE="/etc/X11/Xwrapper.config.bak"
XWRAPPER_FILE="/etc/X11/Xwrapper.config"
