#!/bin/bash
#/usr/bin/runXBMC

USER_NAME="xbmc"

if [ "$(pidof X)" ] ; then
	/usr/share/$USER_NAME/xbmc.bin  --standalone
	exit
fi

while true
do
	echo "#!/bin/bash" >  /home/$USER_NAME/.xsession
	echo "/usr/bin/xbmc --standalone" >>  /home/$USER_NAME/.xsession
	echo "case \"\$?\" in" >>  /home/$USER_NAME/.xsession
	echo "    0 ) # Quit" >>  /home/$USER_NAME/.xsession
	echo "        touch /tmp/noRestartXBMC" >> /home/$USER_NAME/.xsession
	echo "        break ;;"  >>  /home/$USER_NAME/.xsession
	echo "    64 ) # Shutdown System"  >>  /home/$USER_NAME/.xsession
	echo "        sleep 10 ;;"  >>  /home/$USER_NAME/.xsession
	echo "    65 ) # Warm Reboot"  >>  /home/$USER_NAME/.xsession
	echo "        echo "Restarting XBMC ..." ;;"  >>  /home/$USER_NAME/.xsession
	echo "    66 ) # Reboot System"  >>  /home/$USER_NAME/.xsession
	echo "        sleep 10 ;;"  >>  /home/$USER_NAME/.xsession
	echo "     * ) ;;"  >>  /home/$USER_NAME/.xsession
	echo "esac"  >>  /home/$USER_NAME/.xsession

	chown $USER_NAME:$USER_NAME /home/$USER_NAME/.xsession

	initctl emit starting-x

	if [ "$(whoami)" == "root" ] ; then
		su xbmc -c "startx -- -br > /dev/null 2>&1" -l
	else
		startx -- -br > /dev/null 2>&1
	fi

	if [ -e /tmp/noRestartXBMC ] ; then
		rm /tmp/noRestartXBMC
		rm /home/$USER_NAME/.xsession
		break
	fi
done

